export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  VERIFICATION_OFFICER = 'VERIFICATION_OFFICER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  CUSTOMER = 'CUSTOMER',
  INDIVIDUAL_PROVIDER = 'INDIVIDUAL_PROVIDER',
  COMPANY_OWNER = 'COMPANY_OWNER',
  COMPANY_MANAGER = 'COMPANY_MANAGER',
  TEAM_MEMBER = 'TEAM_MEMBER',
}

export enum PermissionType {
  // User Management
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_EDIT = 'USER_EDIT',
  USER_SUSPEND = 'USER_SUSPEND',
  USER_DELETE = 'USER_DELETE',

  // Provider & Verification
  PROVIDER_VIEW = 'PROVIDER_VIEW',
  PROVIDER_CREATE = 'PROVIDER_CREATE',
  PROVIDER_EDIT = 'PROVIDER_EDIT',
  PROVIDER_VERIFY = 'PROVIDER_VERIFY',

  // Jobs & Bookings
  JOB_VIEW = 'JOB_VIEW',
  JOB_CREATE = 'JOB_CREATE',
  JOB_EDIT = 'JOB_EDIT',
  JOB_CANCEL = 'JOB_CANCEL',
  BOOKING_VIEW = 'BOOKING_VIEW',
  BOOKING_MANAGE = 'BOOKING_MANAGE',

  // Financial & Payments
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_MANAGE = 'PAYMENT_MANAGE',
  PAYOUT_VIEW = 'PAYOUT_VIEW',
  PAYOUT_APPROVE = 'PAYOUT_APPROVE',
  SUBSCRIPTION_MANAGE = 'SUBSCRIPTION_MANAGE',

  // Disputes & Support
  DISPUTE_VIEW = 'DISPUTE_VIEW',
  DISPUTE_MANAGE = 'DISPUTE_MANAGE',
  SUPPORT_VIEW = 'SUPPORT_VIEW',
  SUPPORT_RESPOND = 'SUPPORT_RESPOND',

  // Content & CMS
  CMS_VIEW = 'CMS_VIEW',
  CMS_EDIT = 'CMS_EDIT',

  // System Administration
  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_EDIT = 'SETTINGS_EDIT',
  FEATURE_FLAG_MANAGE = 'FEATURE_FLAG_MANAGE',
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
}

